version: 1

formatters:
  standard:
    format: '[%(asctime)s] - %(levelname)s - %(name)s/%(filename)s .. %(message)s'
    datefmt: '%D - %H:%M'

handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: application.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf8

root:
  level: ERROR
  handlers: [file]

loggers:
  ArticleSuggestor:
    level: INFO
    handlers: [file]
    propagate: no
